[project]
name = "RadioLive"
version = "0.1.0"
description = "基于 Python Tkinter + VLC 的广播直播桌面客户端"
authors = [

]
requires-python = ">=3.7"
dependencies = [
    "python-vlc",
    "requests"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
