name: Auto Tag

on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]

jobs:
  create_tag:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag | grep ^v | sort -V | tail -1)
          echo "latest_tag=${latest_tag:-v0.0.0}" >> $GITHUB_OUTPUT

      - name: Calculate next tag
        id: calc_tag
        run: |
          old=${{ steps.get_tag.outputs.latest_tag }}
          ver=${old#v}
          IFS='.' read -r major minor patch <<< "${ver:-0.0.0}"
          patch=$((patch+1))
          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git tag ${{ steps.calc_tag.outputs.new_tag }}
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} ${{ steps.calc_tag.outputs.new_tag }}
