name: Auto Tag

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --list 'v*' --sort=-v:refname | head -n1)
          if [ -z "$latest_tag" ]; then
            echo "tag=v1.0.0" >> $GITHUB_OUTPUT
          else
            ver=${latest_tag#v}
            IFS='.' read -r major minor patch <<< "$ver"
            patch=$((patch+1))
            echo "tag=v${major}.${minor}.${patch}" >> $GITHUB_OUTPUT
          fi

      - name: Create new tag and push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.get_tag.outputs.tag }}
          git push origin ${{ steps.get_tag.outputs.tag }}
