name: Build and Release

on:
  workflow_run:
    workflows: [ "Auto Tag" ]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: windows-latest    # 打包 Windows exe
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller --name RadioLive --noconsole --add-data "radios.json;." src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RadioLive
          path: dist/RadioLive/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/RadioLive/RadioLive.exe
          tag_name: ${{ github.event.client_payload.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
